"""initial

Revision ID: 0001_initial
Revises: 
Create Date: 2026-03-24
"""
from alembic import op
import sqlalchemy as sa

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table('users',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table('user_profiles',
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), primary_key=True),
        sa.Column('selected_repeat_area', sa.String(), nullable=True),
        sa.Column('selected_ai_help_type', sa.String(), nullable=True),
        sa.Column('selected_output_preference', sa.String(), nullable=True),
        sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table('captures',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('input_mode', sa.String(), nullable=False),
        sa.Column('tag_hint', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index('idx_captures_user_created_at', 'captures', ['user_id', 'created_at'])
    op.create_table('raw_memories',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('capture_id', sa.String(), sa.ForeignKey('captures.id', ondelete='SET NULL'), nullable=True),
        sa.Column('source', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('signal_type', sa.String(), nullable=True),
        sa.Column('scene_type', sa.String(), nullable=True),
        sa.Column('friction_type', sa.String(), nullable=True),
        sa.Column('emotion_strength', sa.String(), nullable=True),
        sa.Column('repetition_flag', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('desire_flag', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('related_pattern_id', sa.String(), nullable=True),
        sa.Column('related_friction_id', sa.String(), nullable=True),
        sa.Column('metadata_json', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table('patterns',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('scene_type', sa.String(), nullable=True),
        sa.Column('frequency_7d', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('frequency_30d', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('stability_score', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('confidence_score', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(), nullable=False, server_default='candidate'),
        sa.Column('summary_json', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table('frictions',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('friction_type', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('severity_score', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('frequency_7d', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('frequency_30d', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('confidence_score', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('related_pattern_ids', sa.JSON(), nullable=False),
        sa.Column('representative_quotes', sa.JSON(), nullable=False),
        sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(), nullable=False, server_default='candidate'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table('desires',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('mention_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('priority_score', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('related_pattern_ids', sa.JSON(), nullable=False),
        sa.Column('related_friction_ids', sa.JSON(), nullable=False),
        sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table('opportunities',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('related_pattern_ids', sa.JSON(), nullable=False),
        sa.Column('related_friction_ids', sa.JSON(), nullable=False),
        sa.Column('related_desire_ids', sa.JSON(), nullable=False),
        sa.Column('opportunity_type', sa.String(), nullable=True),
        sa.Column('maturity', sa.String(), nullable=False, server_default='candidate'),
        sa.Column('score_total', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('score_repeatability', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('score_pain', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('score_clarity', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('score_desire', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('score_ai_fit', sa.Numeric(4, 3), nullable=False, server_default='0'),
        sa.Column('expected_value', sa.Text(), nullable=True),
        sa.Column('recommendation', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=False, server_default='open'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table('followup_questions',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('raw_memory_id', sa.String(), sa.ForeignKey('raw_memories.id', ondelete='CASCADE'), nullable=True),
        sa.Column('related_pattern_id', sa.String(), nullable=True),
        sa.Column('related_friction_id', sa.String(), nullable=True),
        sa.Column('question_type', sa.String(), nullable=False),
        sa.Column('question_text', sa.Text(), nullable=False),
        sa.Column('options_json', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='available'),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table('followup_answers',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('followup_question_id', sa.String(), sa.ForeignKey('followup_questions.id', ondelete='CASCADE'), nullable=False),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('answer_value', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table('weekly_insights',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('week_start', sa.Date(), nullable=False),
        sa.Column('week_end', sa.Date(), nullable=False),
        sa.Column('status', sa.String(), nullable=False, server_default='available'),
        sa.Column('key_insight', sa.Text(), nullable=True),
        sa.Column('top_patterns_json', sa.JSON(), nullable=False),
        sa.Column('top_frictions_json', sa.JSON(), nullable=False),
        sa.Column('best_action', sa.Text(), nullable=True),
        sa.Column('opportunity_snapshot_json', sa.JSON(), nullable=True),
        sa.Column('feedback_value', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint('user_id', 'week_start', name='uq_weekly_user_week_start'),
    )
    op.create_table('opportunity_feedbacks',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('opportunity_id', sa.String(), sa.ForeignKey('opportunities.id', ondelete='CASCADE'), nullable=False),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('feedback_value', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_table('experiments',
        sa.Column('id', sa.String(), primary_key=True),
        sa.Column('user_id', sa.String(), sa.ForeignKey('users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('opportunity_id', sa.String(), sa.ForeignKey('opportunities.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('hypothesis', sa.Text(), nullable=True),
        sa.Column('action_taken', sa.Text(), nullable=True),
        sa.Column('result_summary', sa.Text(), nullable=True),
        sa.Column('feedback_score', sa.Numeric(4, 3), nullable=True),
        sa.Column('effectiveness_score', sa.Numeric(4, 3), nullable=True),
        sa.Column('status', sa.String(), nullable=False, server_default='active'),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )


def downgrade() -> None:
    for table in ['experiments','opportunity_feedbacks','weekly_insights','followup_answers','followup_questions','opportunities','desires','frictions','patterns','raw_memories','captures','user_profiles','users']:
        op.drop_table(table)
